#
# ui.R
#
# Purpose:    This application creates a shiny app for a natural language processing model 
#             using Kneser-Ney smoothing with calculated continuation probabilities 
#             for the prediction of 'ngrams'
# Created By: Mark A. Jack
# Created On: 11/24/2016
#
library(shiny)

# Create application using results of an ngram word prediction model 
shinyUI(
  fluidPage(
  titlePanel("A word predictions app using 'ngrams' continuation probabilities 
             via Kneser-Ney smoothing in a natural language processing model (NLP)"),
  hr(),
  h4("Instructions:"),
  p("Please type a word or several words in the space below."),
  p("Then press the blue submit button."),
  p("Wait a few seconds until you see the 3 most likely word suggestions"), 
  p("in the grey text box below to follow your input generated by the NLP model."),
  
  hr(),
  
  # Add a text area for the user input.
  h4("Input Text:"),
  tags$textarea(id="text", rows=1, cols=50, ""),
  p("Please enter your text above."),
  
#  textInput("text", label = h3("Text input"), value = "Enter text..."),
  
  submitButton(text = "Predict the next word ..."),
  
  p('(Example: "arcane" or "the face" or "thanks for the" or "at the same time")'),
  
  hr(),
  
  h4("Your next word prediction is:"),

  fluidRow(column(3, verbatimTextOutput("prediction"))),
  
  hr(),
  
  p("This app uses simplified Kneser-Ney smoothing."),
  hr(),
  p("This app was created by Mark A. Jack."), 
  p("Email: mark [dot] a [dot] jack [at] gmail [dot] com"),

  sidebarLayout(position = "right",
    sidebarPanel(
      helpText("Show frequency plots of 'ngrams' from the selected text corpus."),
      
      selectInput("select", 
                  label = h4("Choose an 'ngrams' statistics to display:"),
                  choices = list("unigrams","bigrams","trigrams","quadgrams"),
                  selected = "unigrams")
      ),
    
    mainPanel(
      plotOutput("distPlot")
    )
  )

))
